# Generated by Django 5.1 on 2024-11-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('wallet', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('address_street', models.CharField(max_length=255)),
                ('address_district', models.CharField(max_length=100)),
                ('father_phone', models.CharField(max_length=50)),
                ('mother_phone', models.CharField(max_length=50)),
                ('adhaarName', models.CharField(max_length=100)),
                ('adhaarPhone', models.CharField(max_length=50)),
                ('adhaarAddress', models.CharField(max_length=255)),
                ('adhaar_beneficiary', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=100)),
                ('bankName', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('adhaar_ct_length', models.PositiveIntegerField(default=0)),
                ('pan_ct_length', models.PositiveIntegerField(default=0)),
                ('bank_ct_length', models.PositiveIntegerField(default=0)),
                ('encrypted_data', models.BinaryField()),
                ('public_key', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
